run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    # Errors
    - errcheck
    - errorlint
    - govet
    - staticcheck
    - typecheck
    - unused
    # Style
    - revive
    - gofmt
    - goimports
    - whitespace
    - godot
    # Security
    - gosec
    # Complexity
    - cyclop
    - gocognit
    - funlen
    # Cleanup
    - unconvert
    - unparam
    - wastedassign
    - bodyclose
    - noctx

linters-settings:
  cyclop:
    max-complexity: 20
  gocognit:
    min-complexity: 20
  funlen:
    lines: 80
    statements: 50
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: var-naming
        disabled: true

issues:
  exclude-dirs:
    - dist
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
